[package]
name = "canal-rs"
version = "0.1.0"
authors = ["YahanLin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "2", features = ["with-bytes"] }

[dependencies.async-std]
version = "1.0.1"
features = ["unstable"]
